
-- ATELIER NOURA FINAL DATABASE
-- Run in Supabase SQL Editor.
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role text not null default 'customer' check (role in ('customer','owner')),
  created_at timestamptz not null default now()
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  name_ar text not null,
  name_fr text not null,
  name_en text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  category_id bigint references public.categories(id) on delete set null,
  name_ar text not null,
  name_fr text not null,
  name_en text not null,
  description_ar text,
  description_fr text,
  description_en text,
  price numeric(12,2) not null check (price >= 0),
  stock integer not null default 0 check (stock >= 0),
  is_featured boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.product_images (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  storage_path text not null,
  is_cover boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.delivery_zones (
  id bigint generated by default as identity primary key,
  wilaya text unique not null,
  home_fee numeric(10,2) not null default 0 check (home_fee >= 0),
  office_fee numeric(10,2) not null default 0 check (office_fee >= 0),
  is_active boolean not null default true
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number text unique not null default ('AN-' || upper(substr(replace(gen_random_uuid()::text,'-',''),1,6))),
  customer_name text not null,
  phone text not null,
  wilaya text not null,
  delivery_method text not null check (delivery_method in ('home','office')),
  address text,
  notes text,
  subtotal numeric(12,2) not null check (subtotal >= 0),
  delivery_fee numeric(12,2) not null check (delivery_fee >= 0),
  total numeric(12,2) not null check (total >= 0),
  status text not null default 'new' check (status in ('new','confirmed','preparing','shipped','delivered','cancelled')),
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id bigint not null references public.products(id),
  quantity integer not null check (quantity > 0),
  unit_price numeric(12,2) not null check (unit_price >= 0)
);

alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.product_images enable row level security;
alter table public.delivery_zones enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

-- Public catalog access.
create policy "public read active categories" on public.categories for select using (true);
create policy "public read active products" on public.products for select using (is_active = true);
create policy "public read product images" on public.product_images for select using (true);
create policy "public read delivery zones" on public.delivery_zones for select using (is_active = true);

-- Owner policies. Owner status comes from profiles.
create or replace function public.is_owner()
returns boolean language sql stable security definer set search_path = public
as $$ select exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='owner'); $$;

create policy "owner read all orders" on public.orders for select using (public.is_owner());
create policy "owner update orders" on public.orders for update using (public.is_owner()) with check (public.is_owner());
create policy "owner read order items" on public.order_items for select using (public.is_owner());

create policy "owner manage products" on public.products for all using (public.is_owner()) with check (public.is_owner());
create policy "owner manage categories" on public.categories for all using (public.is_owner()) with check (public.is_owner());
create policy "owner manage product images" on public.product_images for all using (public.is_owner()) with check (public.is_owner());
create policy "owner manage delivery" on public.delivery_zones for all using (public.is_owner()) with check (public.is_owner());
create policy "owner read profiles" on public.profiles for select using (public.is_owner() or id=auth.uid());

-- IMPORTANT:
-- For production, create orders through a SECURITY DEFINER RPC/Edge Function
-- that receives product IDs + quantities, reads prices from products,
-- reads delivery_zones, calculates subtotal/fee/total, checks stock,
-- inserts order + order_items atomically, and never trusts client totals.
