
const demoProducts=[
["Noura Tote","bags","4,800 DA"],["Lina Mini","bags","3,600 DA"],["Sahara Skirt","skirts","6,200 DA"],["Noura Scarf","accessories","2,200 DA"]
];
function adminRender(tab="overview"){
const root=document.getElementById("adminApp");
const order=JSON.parse(localStorage.getItem("demoOrder")||"null");
if(tab==="overview")root.innerHTML=`<p class="eyebrow">ATELIER NOURA</p><h1 class="dash-title">Owner Studio</h1><div class="stats"><div class="stat"><span>Products</span><b>${demoProducts.length}</b></div><div class="stat"><span>Orders</span><b>${order?1:0}</b></div><div class="stat"><span>Media</span><b>${JSON.parse(localStorage.getItem("media")||"[]").length}</b></div><div class="stat"><span>Status</span><b>Ready</b></div></div><div class="admin-card"><h3>Welcome back.</h3><p>هذه الواجهة هي مكان إدارة المتجر. عند ربط Supabase يصبح تسجيل الدخول والمنتجات والطلبات والوسائط حقيقية ومحمية بـRLS.</p></div>`;
if(tab==="products")root.innerHTML=`<p class="eyebrow">CATALOG</p><h1 class="dash-title">Products</h1><div class="admin-card"><table class="admin-table"><thead><tr><th>Product</th><th>Category</th><th>Price</th><th>Action</th></tr></thead><tbody>${demoProducts.map((p,i)=>`<tr><td>${p[0]}</td><td>${p[1]}</td><td>${p[2]}</td><td><button onclick="alert('في النسخة المتصلة: Edit product #${i+1}')">Edit</button></td></tr>`).join("")}</tbody></table></div>`;
if(tab==="orders")root.innerHTML=`<p class="eyebrow">ORDERS</p><h1 class="dash-title">Orders</h1><div class="admin-card">${order?`<table class="admin-table"><tr><th>Order</th><th>Customer</th><th>Wilaya</th><th>Total</th><th>Status</th></tr><tr><td>${order.no}</td><td>${order.data.name}</td><td>${order.data.wilaya}</td><td>${order.total.toLocaleString()} DA</td><td>New</td></tr></table>`:`<div class="empty">لا توجد طلبات محلية حاليًا.</div>`}</div>`;
if(tab==="media")root.innerHTML=`<p class="eyebrow">MEDIA STUDIO</p><h1 class="dash-title">Media</h1><div class="admin-card"><div class="media-upload"><h3>Upload images & videos</h3><p>هذه نسخة محلية للمعاينة. بعد ربط Supabase Storage ستصبح الملفات محفوظة سحابيًا.</p><input id="mediaInput" type="file" accept="image/*,video/*" multiple></div><div id="mediaList" class="media-list"></div></div>`;renderMedia();
if(tab==="settings")root.innerHTML=`<p class="eyebrow">STORE SETTINGS</p><h1 class="dash-title">Settings</h1><div class="admin-card"><label>Store name<input value="Atelier Noura" style="display:block;width:100%;padding:12px;margin-top:8px"></label><p class="form-note">Supabase credentials should be placed only in js/supabase.js using the public anon/publishable key. Never place the service role key in frontend code.</p></div>`;
}
function renderMedia(){const list=JSON.parse(localStorage.getItem("media")||"[]");const el=document.getElementById("mediaList");if(!el)return;el.innerHTML=list.map((x,i)=>`<div class="media-box"><button onclick="deleteMedia(${i})">×</button><span>${x.name}</span></div>`).join("");document.getElementById("mediaInput")?.addEventListener("change",e=>{const arr=JSON.parse(localStorage.getItem("media")||"[]");[...e.target.files].forEach(f=>arr.push({name:f.name,type:f.type}));localStorage.setItem("media",JSON.stringify(arr));renderMedia()})}
function deleteMedia(i){const a=JSON.parse(localStorage.getItem("media")||"[]");a.splice(i,1);localStorage.setItem("media",JSON.stringify(a));renderMedia()}
document.addEventListener("DOMContentLoaded",()=>{adminRender();document.querySelectorAll(".admin-tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".admin-tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");adminRender(b.dataset.tab)})});
