
const PRODUCTS=[
{id:1,name:"Noura Tote",category:"bags",price:4800,desc:"حقيبة يومية مصنوعة يدويًا بتفاصيل ناعمة."},
{id:2,name:"Lina Mini",category:"bags",price:3600,desc:"حقيبة صغيرة وخفيفة للمشاوير اليومية."},
{id:3,name:"Sahara Skirt",category:"skirts",price:6200,desc:"تنورة بقصة هادئة ولمسة أنثوية."},
{id:4,name:"Noura Scarf",category:"accessories",price:2200,desc:"إكسسوار بسيط لإكمال الإطلالة."},
{id:5,name:"Atelier Pouch",category:"accessories",price:2800,desc:"حافظة متعددة الاستخدامات."},
{id:6,name:"Dune Skirt",category:"skirts",price:5900,desc:"تصميم مريح مستوحى من الألوان الترابية."}
];
const WILAYAS=["أدرار","الشلف","الأغواط","أم البواقي","باتنة","بجاية","بسكرة","بشار","البليدة","البويرة","تمنراست","تبسة","تلمسان","تيارت","تيزي وزو","الجزائر","الجلفة","جيجل","سطيف","سعيدة","سكيكدة","سيدي بلعباس","عنابة","قالمة","قسنطينة","المدية","مستغانم","المسيلة","معسكر","ورقلة","وهران","البيض","إليزي","برج بوعريريج","بومرداس","الطارف","تندوف","تيسمسيلت","الوادي","خنشلة","سوق أهراس","تيبازة","ميلة","عين الدفلى","النعامة","عين تموشنت","غليزان","تيميمون","برج باجي مختار","أولاد جلال","بني عباس","عين صالح","عين قزام","تقرت","جانت","المغير","المنيعة"];
const money=n=>new Intl.NumberFormat("fr-DZ").format(n)+" DA";
function getCart(){return JSON.parse(localStorage.getItem("cart")||"[]")}
function saveCart(c){localStorage.setItem("cart",JSON.stringify(c));updateCartCount()}
function updateCartCount(){document.querySelectorAll("#cartCount").forEach(e=>e.textContent=getCart().reduce((a,x)=>a+x.qty,0))}
function addToCart(id,qty=1){const p=PRODUCTS.find(x=>x.id==id);if(!p)return;let c=getCart(),item=c.find(x=>x.id==id);item?item.qty+=qty:c.push({id:p.id,qty});saveCart(c);const b=document.querySelector(`[data-add="${id}"]`);if(b){b.textContent="✓";setTimeout(()=>b.textContent="+",900)}}
function productCard(p){return `<article class="product-card"><a href="product.html?id=${p.id}"><div class="product-image"><span class="product-number">0${p.id}</span></div></a><button class="add" data-add="${p.id}" onclick="addToCart(${p.id})">+</button><div class="product-info"><h3>${p.name}</h3><p>${p.desc}</p><div class="price">${money(p.price)}</div></div></article>`}
function renderProducts(list=PRODUCTS,target="productsGrid"){const el=document.getElementById(target);if(el)el.innerHTML=list.map(productCard).join("")}
function initProductsPage(){let current=new URLSearchParams(location.search).get("category")||"all";const grid=document.getElementById("productsGrid");if(!grid)return;function refresh(){let a=current==="all"?PRODUCTS:PRODUCTS.filter(p=>p.category===current);const s=document.getElementById("sort")?.value;if(s==="low")a.sort((x,y)=>x.price-y.price);if(s==="high")a.sort((x,y)=>y.price-x.price);renderProducts(a)}document.querySelectorAll(".filter").forEach(b=>b.addEventListener("click",()=>{current=b.dataset.cat;document.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");refresh()}));document.getElementById("sort")?.addEventListener("change",refresh);const f=document.querySelector(`[data-cat="${current}"]`);if(f)f.classList.add("active");refresh()}
function initHome(){const g=document.getElementById("featuredGrid");if(g)renderProducts(PRODUCTS.slice(0,4),"featuredGrid")}
function initDetail(){const el=document.getElementById("productDetail");if(!el)return;const p=PRODUCTS.find(x=>x.id==new URLSearchParams(location.search).get("id"))||PRODUCTS[0];el.innerHTML=`<div class="product-detail"><div class="detail-image">ATELIER<br>NO.0${p.id}</div><div class="detail-info"><p class="eyebrow">${p.category.toUpperCase()}</p><h1>${p.name}</h1><div class="price">${money(p.price)}</div><p class="description">${p.desc}<br><br>قطعة مصنوعة بعناية، وقد تختلف التفاصيل قليلًا لأن كل قطعة لها طابعها الخاص.</p><div class="qty"><button id="minus">−</button><b id="qty">1</b><button id="plus">+</button></div><button class="btn btn-dark" id="buy">أضيفي إلى الحقيبة</button></div></div>`;let q=1;const qel=document.getElementById("qty");document.getElementById("plus").onclick=()=>{q++;qel.textContent=q};document.getElementById("minus").onclick=()=>{q=Math.max(1,q-1);qel.textContent=q};document.getElementById("buy").onclick=()=>{addToCart(p.id,q);location.href="cart.html"}}
function initCart(){const el=document.getElementById("cartView");if(!el)return;const c=getCart();if(!c.length){el.innerHTML='<div class="empty"><h2>حقيبتك فارغة</h2><p>اكتشفي قطع Atelier Noura.</p><a class="btn btn-dark" href="products.html">المتجر</a></div>';return}let total=0;const rows=c.map(x=>{const p=PRODUCTS.find(z=>z.id==x.id);total+=p.price*x.qty;return `<div class="cart-item"><div class="cart-thumb"></div><div><h3>${p.name}</h3><p>${x.qty} × ${money(p.price)}</p></div><div><b>${money(p.price*x.qty)}</b><button class="remove" onclick="removeCart(${p.id})">حذف</button></div></div>`}).join("");el.innerHTML=`<div class="cart-layout"><div>${rows}</div><aside class="summary-card"><h2>ملخص الطلب</h2><div class="summary-row"><span>المنتجات</span><b>${money(total)}</b></div><div class="summary-row"><span>التوصيل</span><span>يحسب حسب الولاية</span></div><div class="summary-row summary-total"><span>الإجمالي</span><b>${money(total)}</b></div><a class="btn btn-dark full" href="checkout.html">متابعة الطلب</a></aside></div>`}
function removeCart(id){saveCart(getCart().filter(x=>x.id!=id));initCart()}
function initCheckout(){const f=document.getElementById("checkoutForm");if(!f)return;const w=document.getElementById("wilaya");WILAYAS.forEach(x=>w.add(new Option(x,x)));const c=getCart();let total=c.reduce((s,x)=>{const p=PRODUCTS.find(z=>z.id==x.id);return s+p.price*x.qty},0);document.getElementById("checkoutSummary").innerHTML=`<h2>طلبك</h2>${c.map(x=>{const p=PRODUCTS.find(z=>z.id==x.id);return `<div class="summary-row"><span>${p.name} × ${x.qty}</span><b>${money(p.price*x.qty)}</b></div>`}).join("")}<div class="summary-row summary-total"><span>Subtotal</span><b>${money(total)}</b></div><p class="form-note">سيتم تحديد Delivery Fee حسب الولاية في قاعدة البيانات عند تفعيل Supabase.</p>`;f.onsubmit=e=>{e.preventDefault();if(!c.length){alert("السلة فارغة");return}const data=Object.fromEntries(new FormData(f));const no="AN-"+Date.now().toString().slice(-6);localStorage.setItem("lastOrder",no);localStorage.setItem("demoOrder",JSON.stringify({no,data,items:c,total}));localStorage.removeItem("cart");location.href="order-success.html"}}
document.addEventListener("DOMContentLoaded",()=>{updateCartCount();initHome();initProductsPage();initDetail();initCart();initCheckout();document.getElementById("menuBtn")?.addEventListener("click",()=>document.querySelector(".nav")?.classList.toggle("show"))});
